import { Fragment, useCallback, useEffect, useRef, useState, type FormEvent, type PointerEvent as ReactPointerEvent } from 'react';
import { io } from 'socket.io-client';
import type { CanvasAction, DrawSegment, FillAction, GameSettings, RoomView, ShapeAction, ShapeKind } from '@garabato/shared';
import { audioIsMuted, playGameSound, setAudioMuted, startBackgroundMusic } from './audio';

const socket=io({autoConnect:true});
type Chat={id:string;name?:string;text:string;system?:boolean};
type TurnGuess={playerId:string;name:string;position:number;points:number};
// sessionStorage mantiene la identidad al recargar, pero permite que dos pestañas
// del mismo navegador representen jugadores distintos. Guardamos también la
// identidad más reciente en localStorage como respaldo persistente.
const savedId=sessionStorage.getItem('garabato-player-id')||crypto.randomUUID();
sessionStorage.setItem('garabato-player-id',savedId);
localStorage.setItem('garabato-player-id',savedId);

type CanvasTool = 'pen' | 'eraser' | 'fill' | ShapeKind;
const shapeChoices:{kind:ShapeKind;icon:string;label:string}[]=[
  {kind:'circle',icon:'○',label:'Círculo'},
  {kind:'square',icon:'□',label:'Cuadrado'},
  {kind:'triangle',icon:'△',label:'Triángulo'},
  {kind:'star',icon:'☆',label:'Estrella'}
];
const isShapeTool=(tool:CanvasTool):tool is ShapeKind=>shapeChoices.some(choice=>choice.kind===tool);

function Canvas({canDraw}:{canDraw:boolean}){
  const ref=useRef<HTMLCanvasElement>(null),drawing=useRef(false),start=useRef<{x:number;y:number}|null>(null),last=useRef<{x:number;y:number}|null>(null),strokeId=useRef<string|null>(null),preview=useRef<ShapeAction|null>(null),history=useRef<CanvasAction[]>([]);
  const [color,setColor]=useState('#25242a'),[width,setWidth]=useState(6),[opacity,setOpacity]=useState(1),[tool,setTool]=useState<CanvasTool>('pen');
  const chooseTool=(next:CanvasTool)=>{playGameSound('toolClick');setTool(next)};

  const paint=useCallback((segment:DrawSegment)=>{const canvas=ref.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;ctx.save();ctx.globalAlpha=segment.tool==='eraser'?1:(segment.opacity??1);ctx.beginPath();ctx.moveTo(segment.from.x*canvas.width,segment.from.y*canvas.height);ctx.lineTo(segment.to.x*canvas.width,segment.to.y*canvas.height);ctx.strokeStyle=segment.tool==='eraser'?'#fffdf7':segment.color;ctx.lineWidth=segment.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.stroke();ctx.restore()},[]);
  const drawShape=useCallback((action:ShapeAction)=>{const canvas=ref.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;const x1=action.from.x*canvas.width,y1=action.from.y*canvas.height,x2=action.to.x*canvas.width,y2=action.to.y*canvas.height,side=Math.max(2,Math.min(Math.abs(x2-x1),Math.abs(y2-y1))),left=x2>=x1?x1:x1-side,top=y2>=y1?y1:y1-side,cx=left+side/2,cy=top+side/2;ctx.save();ctx.globalAlpha=action.opacity??1;ctx.strokeStyle=action.color;ctx.lineWidth=action.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();if(action.shape==='circle')ctx.arc(cx,cy,side/2,0,Math.PI*2);if(action.shape==='square')ctx.rect(left,top,side,side);if(action.shape==='triangle'){ctx.moveTo(cx,top);ctx.lineTo(left+side,top+side);ctx.lineTo(left,top+side);ctx.closePath()}if(action.shape==='star'){for(let point=0;point<10;point++){const angle=-Math.PI/2+point*Math.PI/5,radius=point%2===0?side/2:side*.22,x=cx+Math.cos(angle)*radius,y=cy+Math.sin(angle)*radius;if(point===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.closePath()}ctx.stroke();ctx.restore()},[]);
  const clear=useCallback(()=>{const canvas=ref.current,ctx=canvas?.getContext('2d');if(canvas&&ctx){ctx.save();ctx.globalAlpha=1;ctx.fillStyle='#fffdf7';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.restore()}},[]);
  const fillArea=useCallback((fill:FillAction)=>{const canvas=ref.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;const image=ctx.getImageData(0,0,canvas.width,canvas.height),data=image.data,w=canvas.width,h=canvas.height,sx=Math.min(w-1,Math.max(0,Math.floor(fill.x*w))),sy=Math.min(h-1,Math.max(0,Math.floor(fill.y*h))),startIndex=(sy*w+sx)*4,target=[data[startIndex],data[startIndex+1],data[startIndex+2],data[startIndex+3]],rgb=[parseInt(fill.color.slice(1,3),16),parseInt(fill.color.slice(3,5),16),parseInt(fill.color.slice(5,7),16)],alpha=fill.opacity??1;if(target.slice(0,3).every((value,index)=>value===rgb[index]))return;const match=(x:number,y:number)=>{const index=(y*w+x)*4;return Math.abs(data[index]-target[0])<=18&&Math.abs(data[index+1]-target[1])<=18&&Math.abs(data[index+2]-target[2])<=18&&Math.abs(data[index+3]-target[3])<=18},set=(x:number,y:number)=>{const index=(y*w+x)*4;data[index]=Math.round(rgb[0]*alpha+data[index]*(1-alpha));data[index+1]=Math.round(rgb[1]*alpha+data[index+1]*(1-alpha));data[index+2]=Math.round(rgb[2]*alpha+data[index+2]*(1-alpha));data[index+3]=255},stack:Array<[number,number]>=[[sx,sy]];while(stack.length){const [px,py]=stack.pop()!;let x=px;while(x>=0&&match(x,py))x--;x++;let up=false,down=false;for(;x<w&&match(x,py);x++){set(x,py);if(py>0){if(match(x,py-1)){if(!up){stack.push([x,py-1]);up=true}}else up=false}if(py<h-1){if(match(x,py+1)){if(!down){stack.push([x,py+1]);down=true}}else down=false}}}ctx.putImageData(image,0,0)},[]);
  const redraw=useCallback(()=>{clear();history.current.forEach(action=>{if(action.tool==='fill')fillArea(action);else if(action.tool==='shape')drawShape(action);else paint(action)})},[clear,drawShape,fillArea,paint]);

  useEffect(()=>{const resize=()=>{const canvas=ref.current;if(!canvas)return;const box=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,2);canvas.width=box.width*ratio;canvas.height=box.height*ratio;redraw()};resize();window.addEventListener('resize',resize);const segment=(action:DrawSegment)=>{history.current.push(action);paint(action)},fill=(action:FillAction)=>{history.current.push(action);fillArea(action)},shape=(action:ShapeAction)=>{history.current.push(action);drawShape(action)},reset=()=>{history.current=[];clear()},undo=(id:string)=>{history.current=history.current.filter(action=>action.id!==id);redraw()},sync=(items:CanvasAction[])=>{history.current=items;redraw()},key=(event:KeyboardEvent)=>{if(canDraw&&(event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();socket.emit('canvas:undo')}};socket.on('draw:segment',segment);socket.on('draw:fill',fill);socket.on('draw:shape',shape);socket.on('canvas:clear',reset);socket.on('canvas:undo',undo);socket.on('canvas:history',sync);window.addEventListener('keydown',key);socket.emit('canvas:sync');return()=>{window.removeEventListener('resize',resize);window.removeEventListener('keydown',key);socket.off('draw:segment',segment);socket.off('draw:fill',fill);socket.off('draw:shape',shape);socket.off('canvas:clear',reset);socket.off('canvas:undo',undo);socket.off('canvas:history',sync)}},[canDraw,clear,drawShape,fillArea,paint,redraw]);

  const pos=(event:ReactPointerEvent)=>{const box=ref.current!.getBoundingClientRect();return{x:(event.clientX-box.left)/box.width,y:(event.clientY-box.top)/box.height}};
  const down=(event:ReactPointerEvent)=>{if(!canDraw)return;const point=pos(event);if(tool==='fill'){const action:FillAction={id:crypto.randomUUID(),x:point.x,y:point.y,color,opacity,tool:'fill'};history.current.push(action);fillArea(action);socket.emit('draw:fill',action);return}drawing.current=true;strokeId.current=crypto.randomUUID();start.current=point;last.current=point;preview.current=null;event.currentTarget.setPointerCapture(event.pointerId)};
  const move=(event:ReactPointerEvent)=>{if(!drawing.current||!last.current||!strokeId.current||!canDraw)return;const next=pos(event);if(isShapeTool(tool)&&start.current){const action:ShapeAction={id:strokeId.current,from:start.current,to:next,color,width,opacity,tool:'shape',shape:tool};preview.current=action;redraw();drawShape(action);return}const drawTool:'pen'|'eraser'=tool==='eraser'?'eraser':'pen',segment:DrawSegment={id:strokeId.current,from:last.current,to:next,color,width,opacity:drawTool==='eraser'?1:opacity,tool:drawTool};history.current.push(segment);paint(segment);socket.emit('draw:segment',segment);last.current=next};
  const up=()=>{if(preview.current){const action=preview.current;history.current.push(action);socket.emit('draw:shape',action);preview.current=null;redraw()}drawing.current=false;start.current=null;last.current=null;strokeId.current=null};

  return <div className="canvas-shell">
    <canvas ref={ref} aria-label="Lienzo de dibujo" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/>
    {canDraw&&<div className="tools" aria-label="Herramientas de dibujo">
      <div className="basic-tools"><button className={tool==='pen'?'selected':''} aria-pressed={tool==='pen'} onClick={()=>chooseTool('pen')} title="Lápiz">✎</button><button className={tool==='eraser'?'selected':''} aria-pressed={tool==='eraser'} onClick={()=>chooseTool('eraser')} title="Borrador">◇</button><button className={tool==='fill'?'selected':''} aria-pressed={tool==='fill'} onClick={()=>chooseTool('fill')} title="Cubeta: rellenar un área">▰</button></div>
      <div className="shape-tools" aria-label="Formas">{shapeChoices.map(choice=><button key={choice.kind} className={tool===choice.kind?'selected':''} aria-pressed={tool===choice.kind} onClick={()=>chooseTool(choice.kind)} title={choice.label} aria-label={choice.label}>{choice.icon}</button>)}</div>
      <div className="colors">{['#25242a','#ef5b4c','#167d91','#efaa32','#6d4bb4','#3b8c57'].map(option=><button key={option} aria-label={`Color ${option}`} className={color===option?'selected':''} style={{background:option}} onClick={()=>setColor(option)}/>)}<label className="custom-color" title="Crear un color"><span>+</span><input type="color" aria-label="Crear un color personalizado" value={color} onChange={event=>setColor(event.target.value)}/></label></div>
      <label className="range width-range"><span>Trazo {width}</span><input aria-label="Grosor del trazo" type="range" min="2" max="24" value={width} onChange={event=>setWidth(+event.target.value)}/></label>
      <label className="range opacity-range"><span>Opacidad {Math.round(opacity*100)}%</span><input aria-label="Opacidad del color" type="range" min="20" max="100" step="10" value={opacity*100} onChange={event=>setOpacity(+event.target.value/100)}/></label>
      <div className="history-tools"><button onClick={()=>socket.emit('canvas:undo')} title="Deshacer la última acción (Ctrl+Z)">↶</button><button onClick={()=>socket.emit('canvas:clear')} title="Limpiar">Limpiar</button></div>
    </div>}
  </div>
}

function Home({error}:{error:string}){
  const [name,setName]=useState(localStorage.getItem('garabato-name')||''),[code,setCode]=useState(new URLSearchParams(location.search).get('sala')||'');
  const submit=(kind:'create'|'join')=>{const clean=name.trim();if(!clean)return;startBackgroundMusic();localStorage.setItem('garabato-name',clean);socket.emit(kind==='create'?'room:create':'room:join',{name:clean,code,playerId:savedId})};
  return <main className="home"><section className="hero"><div className="brand-mark">G!</div><p className="eyebrow">Dibuja · Adivina · Ríete</p><h1>Garabato<br/><i>Club</i></h1><p className="lead">Una mesa de dibujo virtual para esas noches con amigos en las que nadie sabe dibujar — y eso es lo mejor.</p></section>
    <section className="entry card"><div className="tape"/><h2>¿Cómo te llamamos?</h2><label>Tu nombre<input autoFocus maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. Dani" onKeyDown={e=>e.key==='Enter'&&submit('create')}/></label><button className="primary" onClick={()=>submit('create')}>Crear una sala <span>→</span></button><div className="or"><span>o entra con un código</span></div><div className="join-row"><label className="sr-only" htmlFor="code">Código de sala</label><input id="code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABC12"/><button onClick={()=>submit('join')}>Unirme</button></div>{error&&<p className="error" role="alert">{error}</p>}<p className="fine">Sin cuentas. Sin descargas. Sólo comparte el código.</p></section></main>
}

function Lobby({room,me}:{room:RoomView;me:string}){
  const mine=room.players.find(p=>p.id===me),[words,setWords]=useState(''),[settings,setSettings]=useState(room.settings),[copied,setCopied]=useState(false);
  useEffect(()=>{setSettings(room.settings)},[room.settings]);
  const update=(patch:Partial<GameSettings>)=>{const next={...settings,...patch};setSettings(next);socket.emit('room:update',{settings:next,words})};
  const wordChange=(value:string)=>{setWords(value);socket.emit('room:update',{settings,words:value})};
  const link=`${location.origin}${location.pathname}?sala=${room.code}`;
  return <main className="room-page"><header className="topbar"><div className="mini-brand">G!</div><div><span>Sala privada</span><strong>{room.code}</strong></div><button className="copy" onClick={async()=>{await navigator.clipboard.writeText(link);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?'¡Copiado!':'Copiar enlace'}</button></header>
    <div className="lobby-grid"><section className="card players-card"><p className="eyebrow">La pandilla</p><h2>{room.players.length} jugadores</h2><div className="player-list">{room.players.map((p,i)=><div className="player" key={p.id}><span className={`avatar a${i%5}`}>{p.name[0]?.toUpperCase()}</span><b>{p.name}{p.id===me?' (tú)':''}</b>{p.isHost&&<small>Anfitrión</small>}<i className={p.connected?'online':'offline'}/></div>)}</div><p className="code-note">Comparte <b>{room.code}</b> para invitar a alguien</p></section>
      <section className="card setup"><p className="eyebrow">Reglas de la mesa</p><h2>Prepara la partida</h2>{mine?.isHost?<>
        <div className="form-grid"><label>Rondas<input type="number" min="1" max="10" value={settings.rounds} onChange={e=>update({rounds:+e.target.value})}/></label><label>Segundos por turno<input type="number" min="30" max="180" step="10" value={settings.turnSeconds} onChange={e=>update({turnSeconds:+e.target.value})}/></label><label>Opciones de palabra<input type="number" min="2" max="5" value={settings.wordOptions} onChange={e=>update({wordOptions:+e.target.value})}/></label><label>Máximo de jugadores<input type="number" min="2" max="12" value={settings.maxPlayers} onChange={e=>update({maxPlayers:+e.target.value})}/></label></div>
        <fieldset><legend>Banco de palabras</legend><label className="radio"><input type="radio" checked={settings.wordMode==='mixed'} onChange={()=>update({wordMode:'mixed'})}/> Mezclar predeterminadas y mías</label><label className="radio"><input type="radio" checked={settings.wordMode==='custom'} onChange={()=>update({wordMode:'custom'})}/> Usar únicamente las mías</label><textarea value={words} onChange={e=>wordChange(e.target.value)} placeholder={'satélite, tostadora, dragón\no una palabra por línea'}/><span className="word-count">{room.customWordCount} palabras personalizadas válidas</span></fieldset>
        <label className="check"><input type="checkbox" checked={settings.allowRepeats} onChange={e=>update({allowRepeats:e.target.checked})}/> Permitir repetir palabras</label><button className="primary start" onClick={()=>socket.emit('game:start')}>Empezar partida <span>✦</span></button></>:<div className="waiting"><span className="scribble">⌁</span><h3>El anfitrión está preparando todo</h3><p>Mientras tanto, practica tu mejor dibujo de un ornitorrinco.</p></div>}</section></div></main>
}

function WordHint({hint}:{hint:string}) {
  const words=hint.split('|');
  return <span className="hint-phrase" aria-label={`Pista: ${words.map(word=>`${word.length} letras`).join(', espacio, ')}`}>
    {words.map((word,index)=><Fragment key={`${index}-${word}`}>
      {index>0&&<span className="space-marker" aria-label="espacio">ESPACIO</span>}
      <span className="hint-group" aria-hidden="true"><span className="hint-word">{[...word].map((letter,letterIndex)=><span className={`hint-letter ${letter==='_'?'unknown':''}`} key={letterIndex}>{letter==='_'?'\u00a0':letter}</span>)}</span><span className="hint-count">{word.length} letras</span></span>
    </Fragment>)}
  </span>;
}

function Game({room,me}:{room:RoomView;me:string}){
  const [options,setOptions]=useState<string[]>([]),[secret,setSecret]=useState(''),[chat,setChat]=useState<Chat[]>([]),[text,setText]=useState(''),[now,setNow]=useState(Date.now()),[lastWord,setLastWord]=useState(''),[turnGuesses,setTurnGuesses]=useState<TurnGuess[]>([]),[guessNotice,setGuessNotice]=useState(false),[nearNotice,setNearNotice]=useState(0);
  const scroll=useRef<HTMLDivElement>(null),answerRef=useRef<HTMLInputElement>(null),lastCountdownSound=useRef(''),lastTurnStartSound=useRef(0),drawer=room.players.find(p=>p.id===room.drawerId),isDrawer=room.drawerId===me;
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),250);const opts=(x:string[])=>{setOptions(x);setTurnGuesses([])},sec=(x:string)=>{setSecret(x);setOptions([])},message=(x:{id:string;name:string;text:string})=>setChat(c=>[...c.slice(-60),x]),system=(x:string)=>setChat(c=>[...c.slice(-60),{id:crypto.randomUUID(),text:x,system:true}]),near=()=>setNearNotice(value=>value+1),ended=(x:{word:string;guesses:TurnGuess[]})=>{setLastWord(x.word);setTurnGuesses(x.guesses||[]);setSecret('');setOptions([])};socket.on('turn:options',opts);socket.on('turn:secret',sec);socket.on('chat:message',message);socket.on('chat:system',system);socket.on('chat:near',near);socket.on('turn:ended',ended);socket.emit('turn:sync');return()=>{clearInterval(timer);socket.off('turn:options',opts);socket.off('turn:secret',sec);socket.off('chat:message',message);socket.off('chat:system',system);socket.off('chat:near',near);socket.off('turn:ended',ended)}},[]);
  useEffect(()=>{if(isDrawer&&(room.phase==='choosing'||room.phase==='drawing'))socket.emit('turn:sync')},[isDrawer,room.phase,room.drawerId]);
  useEffect(()=>{const sync=()=>socket.emit('room:sync'),visible=()=>{if(document.visibilityState==='visible')sync()};const timer=setInterval(sync,3000);window.addEventListener('focus',sync);document.addEventListener('visibilitychange',visible);sync();return()=>{clearInterval(timer);window.removeEventListener('focus',sync);document.removeEventListener('visibilitychange',visible)}},[]);
  useEffect(()=>{if(room.phase==='turnEnd'){if(room.lastWord)setLastWord(room.lastWord);if(room.turnResults)setTurnGuesses(room.turnResults)}},[room.phase,room.lastWord,room.turnResults]);
  useEffect(()=>{if(room.phase!=='drawing'||isDrawer)return;setGuessNotice(true);answerRef.current?.focus();const timer=setTimeout(()=>setGuessNotice(false),2500);return()=>clearTimeout(timer)},[room.phase,room.drawerId,isDrawer]);
  useEffect(()=>{if(!nearNotice)return;const timer=setTimeout(()=>setNearNotice(0),2600);return()=>clearTimeout(timer)},[nearNotice]);
  useEffect(()=>{scroll.current?.scrollTo({top:scroll.current.scrollHeight})},[chat]);
  const deadline=room.phase==='choosing'?room.chooseEndsAt:room.turnEndsAt,remaining=Math.max(0,Math.ceil(((deadline||now)-now)/1000)),typedLetters=[...text].filter(char=>/[\p{L}\p{N}]/u.test(char)).length;const send=(e:FormEvent)=>{e.preventDefault();if(!text.trim())return;socket.emit('chat:send',text);setText('')};
  useEffect(()=>{if(!deadline||!['choosing','drawing'].includes(room.phase)||remaining<=0||remaining>11)return;const key=`${room.phase}:${deadline}`;if(lastCountdownSound.current===key)return;lastCountdownSound.current=key;playGameSound('countdown')},[deadline,remaining,room.phase]);
  useEffect(()=>{if(room.phase!=='drawing'||!room.turnEndsAt||lastTurnStartSound.current===room.turnEndsAt)return;lastTurnStartSound.current=room.turnEndsAt;const totalMs=room.settings.turnSeconds*1000;if(room.turnEndsAt-Date.now()>=totalMs-5000)playGameSound('turnStart')},[room.phase,room.settings.turnSeconds,room.turnEndsAt]);
  if(room.phase==='finished'){const ranking=[...room.players].sort((a,b)=>b.score-a.score);return <main className="results"><div className="card"><p className="eyebrow">Fin de la partida</p><h1>El podio del garabato</h1><div className="podium">{ranking.map((p,i)=><div key={p.id} className={`rank r${i+1}`}><span>{i===0?'★':i+1}</span><b>{p.name}</b><strong>{p.score} pts</strong></div>)}</div><button className="primary" onClick={()=>location.reload()}>Jugar otra vez</button></div></main>}
  return <main className="game"><header className="gamebar"><div className="round"><span>Ronda</span><b>{room.round}/{room.totalRounds}</b></div><div className="turn-title"><span>{isDrawer?'Tu palabra':`${drawer?.name||'Alguien'} dibuja`}</span><strong className={!isDrawer&&room.wordHint?'word-hint':''}>{isDrawer?(secret||'Elige una palabra'):(room.wordHint?<WordHint hint={room.wordHint}/>: 'Preparando…')}</strong>{!isDrawer&&room.phase==='drawing'&&<small>{room.wordLength} letras en total</small>}</div><div className={`timer ${remaining<11?'urgent':''}`}><span>{room.phase==='choosing'?'Para elegir':'Tiempo'}</span><b>{remaining}s</b></div></header>
    {room.phase==='choosing'&&isDrawer&&<div className="choice-overlay"><div className="card"><p className="eyebrow">Sólo tú puedes verlo</p><div className="choice-countdown" aria-live="polite">{remaining}s</div><h2>¿Qué quieres dibujar?</h2><div className="choices">{options.map(x=><button key={x} onClick={()=>socket.emit('turn:choose',x)}>{x}</button>)}</div><small>Si no eliges, escogeremos una por ti.</small></div></div>}
    {room.phase==='choosing'&&!isDrawer&&<div className="choice-overlay waiting-overlay"><div className="card"><span className="scribble">⌁</span><h2>{drawer?.name} está eligiendo palabra</h2><p>El siguiente dibujo comienza en unos segundos.</p></div></div>}
    {room.phase==='turnEnd'&&<div className="turn-summary"><div className="card"><p className="eyebrow">Fin del turno</p><h2>La palabra era <b>{lastWord}</b></h2>{turnGuesses.length?<div className="guess-results">{turnGuesses.map(g=><div key={g.playerId}><span>#{g.position}</span><b>{g.name}</b><strong>+{g.points}</strong></div>)}</div>:<p>Nadie logró adivinar esta vez.</p>}<small>El dibujante recibe 50 puntos por cada acierto.</small></div></div>}
    {guessNotice&&<div className="guess-notice" role="status"><b>¡Ahora adivinas!</b><span>{drawer?.name} está dibujando</span></div>}
    {nearNotice>0&&!room.players.find(player=>player.id===me)?.guessed&&<div className="near-notice" role="status" aria-live="assertive"><b>¡Muy cerca!</b><span>Tu respuesta se parece mucho.</span></div>}
    <section className="board"><Canvas canDraw={isDrawer&&room.phase==='drawing'}/></section>
    <aside className="sidebar"><section className="score-panel"><h2>Marcador</h2>{[...room.players].sort((a,b)=>b.score-a.score).map((p,i)=><div className="score" key={p.id}><span>{i+1}</span><b>{p.name}</b>{p.guessed&&<i title="Ya acertó">✓</i>}<strong>{p.score}</strong></div>)}</section><section className="chat"><h2>Respuestas</h2><div className="messages" ref={scroll} aria-live="polite">{chat.length===0&&<p className="empty">Las respuestas aparecerán aquí.</p>}{chat.map(m=><p key={m.id} className={m.system?'system':''}>{!m.system&&<b>{m.name}: </b>}{m.text}</p>)}</div><div className="answer-entry">{!isDrawer&&room.phase==='drawing'&&<span className="letter-progress" aria-live="polite">({typedLetters}/{room.wordLength||0} letras)</span>}<form onSubmit={send}><input ref={answerRef} aria-label="Escribe tu respuesta" disabled={isDrawer||room.phase!=='drawing'} value={text} onChange={e=>setText(e.target.value)} placeholder={isDrawer?'Estás dibujando':'Escribe tu respuesta…'}/><button aria-label="Enviar respuesta" disabled={isDrawer}>↑</button></form></div></section></aside>
  </main>
}

export default function App(){
  const [room,setRoom]=useState<RoomView|null>(null),[error,setError]=useState(''),[muted,setMuted]=useState(audioIsMuted());
  const previousPhase=useRef<RoomView['phase']|null>(null);
  useEffect(()=>{const joined=({code}:{code:string})=>history.replaceState({},'',`?sala=${code}`),state=(x:RoomView)=>{setRoom(x);setError('')},err=(x:string)=>setError(x),rejoin=()=>{const code=new URLSearchParams(location.search).get('sala'),name=localStorage.getItem('garabato-name');if(code&&name)socket.emit('room:join',{code,name,playerId:savedId})};socket.on('room:joined',joined);socket.on('room:state',state);socket.on('app:error',err);socket.on('connect',rejoin);if(socket.connected)rejoin();return()=>{socket.off('room:joined',joined);socket.off('room:state',state);socket.off('app:error',err);socket.off('connect',rejoin)}},[]);
  useEffect(()=>{if(previousPhase.current==='lobby'&&room?.phase==='choosing')playGameSound('firstStart');previousPhase.current=room?.phase??null},[room?.phase]);
  useEffect(()=>{const unlock=()=>startBackgroundMusic();window.addEventListener('pointerdown',unlock,{once:true});window.addEventListener('keydown',unlock,{once:true});return()=>{window.removeEventListener('pointerdown',unlock);window.removeEventListener('keydown',unlock)}},[]);
  const toggleAudio=()=>{const next=!muted;setMuted(next);setAudioMuted(next)};
  const me=room?.players.find(p=>p.id===savedId);
  return <><a className="skip" href="#main">Saltar al contenido</a><button className="sound-toggle" type="button" onClick={toggleAudio} aria-pressed={muted} aria-label={muted?'Activar sonidos':'Silenciar sonidos'} title={muted?'Activar sonidos':'Silenciar sonidos'}>{muted?'🔇':'🔊'}</button><div id="main">{!room?<Home error={error}/>:room.phase==='lobby'?<Lobby room={room} me={savedId}/>:<Game room={room} me={savedId}/>}</div>{error&&room&&<div className="toast" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>} {!me?.connected&&room&&<div className="connection">Reconectando…</div>}</>;
}
